version: 2

project_name: pxgo

builds:
  - id: pxgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: .
  - id: pxgow
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    binary: pxgow
    ldflags:
      - -s -w -H windowsgui -X main.version={{.Version}}
    main: ./cmd/pxgow

archives:
  - ids: [pxgo, pxgow]
    allow_different_binary_count: true
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

sboms:
  - id: archives
    artifacts: archive

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: khanhkit
    name: pxgo
  draft: false
  prerelease: auto
